### ISSUE TITLE
Module not found in typescript

### ISSUE THREAD

**Issue by angelovdev** [Nebulizer1213/precise-memory-rate-limit#1]
Installed both express-rate-limit and precise-memory-rate-limit and I get the following IDE error on precise-memory-rate-limt:
`Cannot find module 'precise-memory-rate-limit' or its corresponding type declarations.ts(2307)`

This is an API endpoint in Next.js and the file is written in Typescript.
Using the require syntax produces the same results except it's not underlined in the IDE.

```
Module not found: Can't resolve 'precise-memory-rate-limit'
   6 | import rateLimit from "express-rate-limit";
>  8 | import preciseMemory from "precise-memory-rate-limit";
   9 | 
  10 | const apiRequestLimiter = rateLimit({
  11 |   store: preciseMemory(1 * 60 * 1000), // 1 minute

Import trace for requested module:
```

Inside the package.json file the packages are listed as
```json
"express-rate-limit": "^5.5.1",
"precise-memory-rate-limit": "^1.0.1"
```

**Comment by Nebulizer1213** [comment]
I do not have much experience with typescript, so I am not really sure why this is happening. Try changing the version from 1.0.1 to 1.1.3. If that does not help let me know.

**Comment by Nebulizer1213** [comment]
Maybe this article will help https://blog.logrocket.com/common-typescript-module-problems-and-how-to-solve/
