### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by sayus2884** [Nebulizer1213/precise-memory-rate-limit#2]
# Bug Report

`
Error: Cannot find module 'project\path\node_modules\precise-memory-rate-limit\index.js'. Please verify that the package.json has a valid "main" entry
`

### Node version

v14.17.4

### OS

Windows 10

### Code to generate the bug

```js
const preciseMemory = require("precise-memory-rate-limit");
```

### What is expected to happen

Finds the module.

### What actually happens

Module not found. 

Workaround: 
```js
const preciseMemory = require("precise-memory-rate-limit/lib");
```

**Comment by Nebulizer1213** [comment]
@sayus2884 I fixed the issue in the newest version (1.1.4).
